screens:
  sm: 640px
  md: 768px
  lg: 1024px
  xl: 1280px
  '2xl': 1536px
colors:
  red-500: "#ef4444"
  blue-500: "#3b82f6"
  green-500: "#10b981"
spacing:
  1: 4.0
  2: 8.0
  3: 12.0
  4: 16.0
  5: 20.0
  6: 24.0
fontFamily:
  sans: ['ui-sans-serif', 'system-ui']
  serif: ['ui-serif', 'Georgia']
  mono: ['ui-monospace', 'SFMono-Regular']
fontSize:
  sm: 12.0
  base: 16.0
  lg: 18.0
  xl: 24.0
borderRadius:
  none: 0.0
  sm: 2.0
  md: 4.0
  lg: 8.0
  full: 9999.0
boxShadow:
  sm: '0 1px 2px rgba(0, 0, 0, 0.05)'
  md: '0 4px 6px rgba(0, 0, 0, 0.1)'
  lg: '0 10px 15px rgba(0, 0, 0, 0.15)'
