include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - example/**
  errors:
    unused_import: ignore
    unused_element: ignore
    unnecessary_null_comparison: ignore
    deprecated_member_use: ignore
    prefer_conditional_assignment: ignore
    sort_child_properties_last: ignore
    use_key_in_widget_constructors: ignore
    avoid_print: ignore
    annotate_overrides: ignore
    overridden_fields: ignore
    prefer_is_empty: ignore
    unnecessary_import: ignore
    avoid_unnecessary_containers: ignore
    prefer_const_constructors: ignore
    avoid_single_cascade_in_expression_statements: ignore
