targets:
  $default:
    builders:
      flutterwind|page_registry:
        enabled: true
        generate_for:
          - lib/pages/**.dart
          - lib/screens/**.dart
          - lib/views/**.dart

builders:
  page_registry:
    import: "package:flutterwind/src/generators/page_registry_generator.dart"
    builder_factories: ["pageRegistryBuilder"]
    build_extensions: {".dart": [".page.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]